# MongoDB Configuration
spring.data.mongodb.uri=${DATABASE_URL:mongodb+srv://antoniomeic80:NPLmcVRSXNfnj8uv@cluster0.mongodb.net/mixerfm?retryWrites=true&w=majority}

# Disable Liquibase
spring.liquibase.enabled=false

# JWT Configuration
jwt.secret=${JWT_SECRET:your-secret-key}

# Server Configuration
server.port=${PORT:80}

# Firebase Configuration
firebase.credentials.path=${FIREBASE_CONFIG:firebase-credentials.json}
